apiVersion: v1
kind: Secret
metadata:
  name: arangodb-secret
  namespace: kube-prometheus-stack
type: Opaque
data:
  PASSWORD: '<base64-encoded-string>'
  URI: '<base64-encoded-string>'
  USERNAME: '<base64-encoded-string>'
