kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-updater-role
  namespace: kube-prometheus-stack
rules:
  - apiGroups: [""]
    resources:
    - secrets
    verbs:
    - 'patch'
    - 'get'
    - 'list'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: token-updater
  namespace: kube-prometheus-stack
    
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-updater-rb
  namespace: kube-prometheus-stack
subjects:
- kind: ServiceAccount
  name: token-updater
  namespace: kube-prometheus-stack
roleRef:
  kind: Role
  name: token-updater-role
  apiGroup: ""

